---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role avacms
#
AVACMS_GIT_IDENTITY: !!null

AVACMS_DJANGO_SETTINGS_MODULE: "avacms.settings.production"
AVACMS_VERSION: "master"

AVACMS_REPOS:
  - PROTOCOL: "{{ COMMON_GIT_PROTOCOL }}"
    DOMAIN: "{{ COMMON_GIT_MIRROR }}"
    PATH: "{{ COMMON_GIT_PATH }}"
    REPO: avacms.git
    VERSION: "{{ AVACMS_VERSION }}"
    DESTINATION: "{{ avacms_code_dir }}"
    SSH_KEY: "{{ AVACMS_GIT_IDENTITY }}"

AVACMS_GUNICORN_WORKERS: "2"
AVACMS_GUNICORN_EXTRA: ""
AVACMS_GUNICORN_EXTRA_CONF: ""
AVACMS_GUNICORN_WORKER_CLASS: "gevent"

#
# vars are namespaced with the module name.
#
avacms_service_name: "avacms"
avacms_user: "{{ avacms_service_name }}"
avacms_home: "{{ COMMON_APP_DIR }}/{{ avacms_service_name }}"
avacms_code_dir: "{{ avacms_home }}/{{ avacms_service_name }}"
avacms_venv_dir: "{{ avacms_home }}/venvs/{{ avacms_service_name }}"

avacms_gunicorn_host: "127.0.0.1"
avacms_gunicorn_port: "8090"
avacms_gunicorn_timeout: "300"

avacms_log_dir: "{{ COMMON_LOG_DIR }}/{{ avacms_service_name }}"

avacms_requirements_base: "{{ avacms_code_dir }}/requirements"
avacms_requirements:
  - production.txt
  - optional.txt

avacms_role_name: avacms

avacms_environment:
  DJANGO_SETTINGS_MODULE: "{{ AVACMS_DJANGO_SETTINGS_MODULE }}"
  AVACMS_CFG: "{{ COMMON_CFG_DIR }}/{{ avacms_service_name }}.yml"
  PATH: "{{ avacms_venv_dir }}/bin:{{ ansible_env.PATH }}"

#
# OS packages
#

avacms_debian_pkgs: []

avacms_redhat_pkgs: []
