---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role avacms
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#

- name: stub ansible task
  debug: msg="This is a stub task created by the ansible-role role"
  notify: notify me
