---

dependencies:
  - common
  - supervisor
  - role: edx_service
    edx_service_name: "{{ avacms_service_name }}"
    edx_service_config: "{{ AVACMS_SERVICE_CONFIG }}"
    edx_service_user: "{{ avacms_user }}"
    edx_service_home: "{{ avacms_home }}"
