---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role avacms
#
# Overview:
#
#
# Dependencies:
#
#
# Example play:
#
#

- name: stub ansible task
  debug: msg="This is a stub task created by the ansible-role role"
  notify: notify me

- name: create application user
  user: >
    name="{{ avacms_user }}" home="{{ avacms_home }}"
    createhome=no shell=/bin/false
  tags:
    - install
    - install:base

- name: "add gunicorn configuration file"
  template: >
    src=edx/app/avacms/avacms_gunicorn.py.j2
    dest={{ avacms_home }}/avacms_gunicorn.py
  sudo_user: "{{ avacms_user }}"

#- name: checkout ava-cms repo into {{ avacms_code_dir }}
#  git_2_0_1: >
#    dest={{ avacms_code_dir }}
#    repo={{ avacms_platform_repo }}
#    version={{ ava_platform_version }}
#    accept_hostkey=yes
#  sudo_user: "{{ avacms_user }}"
#  environment:
#    GIT_SSH: "{{ avacms_git_ssh }}"
#  register: avacms_platform_checkout
#  tags:
#    - install
#    - install:code

#- name: git clean after checking out ava-cms
#  shell: cd {{ avacms_code_dir }} && git clean -xdf
#  sudo_user: "{{ avacms_user }}"
#  tags:
#    - install
#    - install:code
