---
#
# avacms Configuration
#
#
##
# Defaults for role avacms
#
AVACMS_GIT_IDENTITY: !!null

AVACMS_REPO: https://xp-dev.com/git/ava-cms
AVACMS_DJANGO_SETTINGS_MODULE: "ava_cms.settings.production"
AVACMS_VERSION: "master"

AVACMS_HOSTNAME: 'cms.avadvance.org'
# Database
AVACMS_DB_NAME: 'avacms'
AVACMS_DB_HOST: 'localhost'
AVACMS_DB_USER: 'avacms'
AVACMS_DB_PASS: 'password'

AVACMS_DATABASES:
  default:
    ENGINE: 'django.db.backends.mysql'
    NAME: '{{ AVACMS_DB_NAME }}'
    USER: '{{ AVACMS_DB_USER }}'
    PASSWORD: '{{ AVACMS_DB_PASS }}'
    HOST: '{{ AVACMS_DB_HOST }}'
    PORT: '3306'
    ATOMIC_REQUESTS: true
    CONN_MAX_AGE: 60

avacms_service_name: "avacms"
avacms_user: "{{ avacms_service_name }}"
avacms_home: "{{ COMMON_APP_DIR }}/{{ avacms_service_name }}"
avacms_code_dir: "{{ avacms_home }}/{{ avacms_service_name }}"
avacms_venv_dir: "{{ avacms_home }}/venvs/{{ avacms_service_name }}"

avacms_data_dir: "{{ COMMON_DATA_DIR }}/{{ avacms_service_name }}"
avacms_app_dir: "{{ COMMON_APP_DIR }}/avacms"
avacms_media_dir: "{{ avacms_code_dir }}/media"

avacms_gunicorn_host: "127.0.0.1"
avacms_gunicorn_port: "8090"
avacms_gunicorn_timeout: "300"

avacms_log_dir: "{{ COMMON_LOG_DIR }}/{{ avacms_service_name }}"

avacms_requirements_base: "{{ avacms_code_dir }}/requirements"
avacms_requirements:
  - production.txt
  - optional.txt

avacms_role_name: avacms

#Number of gunicorn worker processes to spawn, as a multiplier to number of virtual cores
avacms_worker_core_mult: 4

avacms_environment:
  DJANGO_SETTINGS_MODULE: "{{ AVACMS_DJANGO_SETTINGS_MODULE }}"
  AVACMS_CFG: "{{ COMMON_CFG_DIR }}/{{ avacms_service_name }}.yml"
  PATH: "{{ avacms_venv_dir }}/bin:{{ ansible_env.PATH }}"

AVACMS_REPOS:
  - PROTOCOL: "{{ COMMON_GIT_PROTOCOL }}"
    DOMAIN: "{{ COMMON_GIT_MIRROR }}"
    PATH: "{{ COMMON_GIT_PATH }}"
    REPO: ava-cms
    VERSION: "{{ AVACMS_VERSION }}"
    DESTINATION: "{{ avacms_code_dir }}"
    SSH_KEY: "{{ AVACMS_GIT_IDENTITY }}"

AVACMS_SERVICE_CONFIG:
  DATABASE_OPTIONS:
    connect_timeout: 10
  DATABASES: '{{ AVACMS_DATABASES }}'
  STATIC_ROOT: "{{ COMMON_DATA_DIR }}/{{ avacms_service_name }}/staticfiles"
  MEDIA_ROOT: '{{ avacms_media_dir }}'
  EMAIL_BACKEND: '{{ AVACMS_EMAIL_BACKEND }}'
  EMAIL_HOST: '{{ AVACMS_EMAIL_HOST }}'
  EMAIL_PORT: '{{ AVACMS_EMAIL_PORT }}'
  EMAIL_USE_TLS: '{{ AVACMS_EMAIL_USE_TLS }}'
  EMAIL_HOST_USER: '{{ AVACMS_EMAIL_HOST_USER }}'
  EMAIL_HOST_PASSWORD: '{{ AVACMS_EMAIL_HOST_PASSWORD }}'
  AVACMS_OAUTH2_CLIENT_ID: '{{ AVA_OAUTH2_CLIENT_ID }}'
  AVACMS_OAUTH2_CLIENT_SECRET: '{{ AVA_OAUTH2_CLIENT_SECRET }}'
#
# OS packages
#

avacms_debian_pkgs: []
avacms_redhat_pkgs: []
